version: "3.8"

services:
  gateway-server:
    build: ./gatewayServer
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./gatewayServer:/usr/src/app

  catalog-server:
    build: ./catalogServer
    ports:
      - "3001:3001"
    networks:
      - my_network
    volumes:
      - ./catalogServer:/usr/src/app

  order-server:
    build: ./orderServer
    ports:
      - "3002:3002"
    networks:
      - my_network
    volumes:
      - ./orderServer:/usr/src/app

networks:
  my_network:
    driver: bridge
